### PR TITLE
Sam mapssiv 1316 prototype support in standalone

### PR DESCRIPTION
**Pull request by rgilcrist**
image
image

Path to Navy PDFs: 
https://github.com/MApSS-DEV/mynavy_uniforms-content/tree/main/PDFs

To test PDFs, 

- rename the PDFs you are testing to pdf1 or pdf2 (See Example/Resources/PDF)
- verify the Example.proj has the following listings

- -	<ItemGroup>
		<None Remove="Resources\PDF\pdf1.pdf" />
		<None Remove="Resources\PDF\pdf2.pdf" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\PDF\pdf1.pdf" />
		<EmbeddedResource Include="Resources\PDF\pdf2.pdf" />
	</ItemGroup>

PDF __pdf2.pdf will crash the system someplace in the XAML. No error message provided

### CODE REVIEW

**Comment by vitalii-vov** [comment]
@rgilcrist thanks for your interest in the library, but your request will not be included. Let me explain from your commits:
1) renaming pdf1 and pdf2 files to pdfA and pdfB - does not bring anything useful; And replacing files that demonstrate the work of the application with phials with different page orientation with the same type of files with coats of arms - is not only useless, but also harmful.
2) adding margins to the demo project plays no role;
3) measuring file size and function execution time is not a task of the demo example, but only introduces unnecessary noise into understanding the code.
4) you have included 94 new files in the project, which are garbage generated by your development environment and should be excluded.

Translated with DeepL.com (free version)

**Comment by vitalii-vov** [comment]
@rgilcrist thanks for your interest in the library, but your request will not be included. Let me explain from your commits:
1) renaming `pdf1` and `pdf2` files to `pdfA` and `pdfB` - does not bring anything useful; And replacing files that demonstrate the work of the application with phials with different page orientation with the same type of files with coats of arms - is not only useless, but also harmful.
2) adding `margins` to the demo project plays no role;
3) measuring file size and function execution time is not a task of the demo example, but only introduces unnecessary noise into understanding the code.
4) you have included **94** new files in the project, which are garbage generated by your development environment and should be excluded.

**Comment by rgilcrist** [comment]
Thanks for the return message. I am new to Git, and I was trying your app for my team. I did not intend to send a PR to you.

Sam

From: vitalii-vov ***@***.***>
Sent: Thursday, May 30, 2024 8:14 PM
To: vitalii-vov/Maui.PDFView ***@***.***>
Cc: Robert Gilcrist ***@***.***>; Mention ***@***.***>
Subject: [External] - Re: [vitalii-vov/Maui.PDFView] Sam mapssiv 1316 prototype support in standalone (PR #1)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@rgilcrist<https://github.com/rgilcrist> thanks for your interest in the library, but your request will not be included. Let me explain from your commits:

  1.  renaming pdf1 and pdf2 files to pdfA and pdfB - does not bring anything useful; And replacing files that demonstrate the work of the application with phials with different page orientation with the same type of files with coats of arms - is not only useless, but also harmful.
  2.  adding margins to the demo project plays no role;
  3.  measuring file size and function execution time is not a task of the demo example, but only introduces unnecessary noise into understanding the code.
  4.  you have included 94 new files in the project, which are garbage generated by your development environment and should be excluded.

Translated with DeepL.com (free version)

**Comment by rgilcrist** [comment]
You are correct on all points. Files A and B were larger test files that I used to substitute. As for the garbage files, that was is error in how the fork was set up, and I didn’t have permission to delete them on our fork. Yes. I was a mess.

If you are interested, what I found was the view works very well up to 10 MB. It fails somewhere between 10 and 15MB.

Sam

From: vitalii-vov ***@***.***>
Sent: Thursday, May 30, 2024 8:18 PM
To: vitalii-vov/Maui.PDFView ***@***.***>
Cc: Robert Gilcrist ***@***.***>; Mention ***@***.***>
Subject: [External] - Re: [vitalii-vov/Maui.PDFView] Sam mapssiv 1316 prototype support in standalone (PR #1)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@rgilcrist<https://github.com/rgilcrist> thanks for your interest in the library, but your request will not be included. Let me explain from your commits:

  1.  renaming pdf1 and pdf2 files to pdfA and pdfB - does not bring anything useful; And replacing files that demonstrate the work of the application with phials with different page orientation with the same type of files with coats of arms - is not only useless, but also harmful.
  2.  adding margins to the demo project plays no role;
  3.  measuring file size and function execution time is not a task of the demo example, but only introduces unnecessary noise into understanding the code.
  4.  you have included 94 new files in the project, which are garbage generated by your development environment and should be excluded.

**Pull request closed without merging**
